spring.application.name=Tutomatch
spring.profiles.active=dev

# Database driver (shared)
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (shared)
spring.jpa.hibernate.ddl-auto=update

# Admin default name (shared)
admin.nombre=Administrador TutoMatch
