# === Desarrollo local ===
spring.datasource.url=jdbc:postgresql://localhost:5432/tutomatch
spring.datasource.username=sch
spring.datasource.password=20042705
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
jwt.secret=clave-secreta-super-segura-para-tutomatch-256-bits-minimo
jwt.expiration=1800000
admin.email=admin@uce.edu.ec
admin.password=AdminPass2026!
